### ISSUE TITLE
undefined reference to `pthread_atfork'

### ISSUE THREAD

**Issue by palandlom** [neo4j/neo4j-go-driver#61]
I have the following error during making of seabolt:
```
./make_release.sh
...
[ 81%] Building C object CMakeFiles/seabolt-cli.dir/src/seabolt-cli/src/main.c.o
[ 82%] Linking C executable bin/seabolt-cli
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
CMakeFiles/seabolt-cli.dir/build.make:86: recipe for target 'bin/seabolt-cli' failed
make[2]: *** [bin/seabolt-cli] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/seabolt-cli.dir/all' failed
make[1]: *** [CMakeFiles/seabolt-cli.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Operating System:** Ubuntu 18.04
**Cmake version**: 3.14.5
**Openssl version**:  1.1.1  

What can I do to get avoid of it?

**Comment by peihongbin** [comment]
I have met the same problem. Any ideas?

**Comment by palandlom** [comment]
I used bolt package: https://github.com/neo4j-drivers/seabolt/releases

**Comment by ali-ince** [comment]
Hi @palandlom, @peihongbin,

Would you please verify if https://github.com/neo4j-drivers/seabolt/pull/78 fixes your problem?

Thanks.

**Comment by iahmedov** [comment]
@ali-ince I am facing similar issue on Ubuntu 18.04

compiling seabolt was successful with patch, but when trying to use generated library in project with `--tags seabolt_static` flag same error is shown

**Comment by ali-ince** [comment]
@iahmedov would you please verify if the latest https://github.com/neo4j-drivers/seabolt/pull/78 resolves the issue on your side as well?

**Comment by shuaiyy** [comment]
> @iahmedov would you please verify if the latest [neo4j-drivers/seabolt#78](https://github.com/neo4j-drivers/seabolt/pull/78) resolves the issue on your side as well?

my build on neo4j-drivers/seabolt:1.7-dev was successful,  but when go build with `--tags seabolt_static` flag same error is shown

 ps: ubuntu18.04, OpenSSL 1.1.1
